/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElCascader: typeof import('element-plus/es')['ElCascader']
  const ElCascader1: typeof import('element-plus/es')['ElCascader1']
  const ElCascaderControl: typeof import('element-plus/es')['ElCascaderControl']
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElRadiosPlugin: typeof import('element-plus/es')['ElRadiosPlugin']
}
